### ISSUE TITLE
Database Issue: Access denied for user 'root'@'127.0.0.1' (using password: YES)

### ISSUE THREAD

**Issue by Omnision** [android-sms-gateway/server#109]
Hello,

while using the docker compose setup I ran into these 2 DB issues.

`db-1       | [Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)`
`db-1       | [Warning] Aborted connection 4 to db: 'sms' user: 'sms' host: '192.168.208.3' (Got an error reading communication packets)`

env variables are correctly propagated into the container > `docker exec -it xx env`
I am able to connect to the database manually via CLI without any issues, both to `root` and `sms` using `mysql -u sms -p`

I tried using the configuration from a similar post ( [Issue with MySQL Access in Docker Compose Deployment](https://github.com/capcom6/android-sms-gateway/issues/72) ) which did not work

I am running **Debian 12**
EDIT 1: I have just tested the same on **Ubuntu 24.04 LTS** , same issue

Here's my config:

config.yml
```
gateway: # gateway config
  mode: private # gateway mode (public - allow anonymous device registration, private - protected registration) [GATEWAY__MODE]
  private_token: 12345 # access token for device registration in private mode [GATEWAY__PRIVATE_TOKEN]
http: # http server config
  listen: 127.0.0.1:3000 # listen address [HTTP__LISTEN]
database: # database
  dialect: mysql # database dialect (only mysql supported at the moment) [DATABASE__DIALECT]
  host: db # database host [DATABASE__HOST]
  port: 3306 # database port [DATABASE__PORT]
  user: sms # database user [DATABASE__USER]
  password: sms # database password [DATABASE__PASSWORD]
  database: sms # database name [DATABASE__DATABASE]
  timezone: Europe/London # database timezone (important for message TTL calculation) [DATABASE__TIMEZONE]
fcm: # firebase cloud messaging config
  credentials_json: "{}" # firebase credentials json (for public mode only) [FCM__CREDENTIALS_JSON]
  timeout_seconds: 1 # push notification send timeout [FCM__DEBOUNCE_SECONDS]
  debounce_seconds: 5 # push notification debounce (>= 5s) [FCM__TIMEOUT_SECONDS]
tasks: # tasks config
  hashing: # hashing task (hashes processed messages for privacy purposes)
    interval_seconds: 15 # hashing interval in seconds [TASKS__HASHING__INTERVAL_SECONDS]
```

docker-compose.yml

```
version: '3.8'
services:
  backend:
    image: capcom6/sms-gateway
    environment:
      - CONFIG_PATH=config.yml
      - HTTP__LISTEN=0.0.0.0:3000
      - DATABASE__HOST=db
      - DATABASE__PORT=3306
      - DATABASE__USER=sms
      - DATABASE__PASSWORD=sms
      - DATABASE__DATABASE=sms
    ports:
      - "80:3000"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=sms
      - MYSQL_DATABASE=sms
      - MYSQL_USER=sms
      - MYSQL_PASSWORD=sms
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-proot",
          "-h",
          "127.0.0.1"
        ]
      timeout: 5s
      retries: 10
    ports:
       - "42333:3306"
volumes:
  mariadb-data:
```

**Comment by capcom6** [comment]
Hello!  

The warnings in your logs are caused by a mismatch in the database health check configuration. Specifically, your `MYSQL_ROOT_PASSWORD` is set to `sms` in the environment variables, but the health check command uses `-proot`, which means it’s trying to connect with the password `root`.  

This mismatch prevents `mysqladmin` from successfully "pinging" the database, causing the service to remain in an unhealthy state. As a result, the main application won’t start because it depends on the database being marked as healthy.
